### ISSUE TITLE
Output nothing on success 

### ISSUE THREAD

**Issue by LOZORD** [ekivolowitz/QTUM-support#1]
Following the Unix "Rule of Silence", you may consider capturing all output and checking return codes (via `$?`), and only printing to stderr if something bad happens. In addition consider using `set -eux` if it is supported on Mac.

**Comment by ekivolowitz** [comment]
Thanks Leo. I'll add that in there.

**Comment by ekivolowitz** [comment]
Removed echos. Did not set the eux flag.
